# config.toml
# https://github.com/CrimsonRay/slender

baseurl = "http://gijskoot.nl/"
title = "gijskoot.nl"
languageCode = "en-US"
MetaDataFormat = "toml"
theme = "slender"
paginate = 3
PaginatePath = "/"

[author]
    name = "Gijs Koot"

[permalinks]

    # Permalink format for pages.
    page = "/:title/"

    # Permalink format for blog posts.
    post = "/article/:title/"

[params]

    # Change the color scheme of Slender.
    # See above for preview and list of color schemes.
    colorscheme = "blue"

    # Tagline; HTML accepted here. Keep it concise.
    tagline = "Homepage"

    # Footer; Markdown accepted here.
    footer = "Copyright 2016 &copy; Gijs Koot; powered by Hugo"

    # Description and keywords for <meta> tags.
    # Remember to set this for your main page.
    # This will be overridden by whatever is set by the page or post,
    # defined by `description` and `keywords` variables in the front matter
    # of the markdown file.
    description = "Default Page Description"
    keywords = "default,page,keywords"

    # Social links, must be full URLs (e.g. https://github.com/CrimsonRay/).
    # Remove, comment, or leave blank any field to leave them out.
    # email = "mailto:your-email"
    # github = "url-to-your-github"
    # bitbucket = "url-to-your-bitbucket"
    twitter = "https://twitter.com/Gijs_Koot"
    stackoverflow = "http://stackoverflow.com/users/1303355/gijs"
    linkedin = "https://linkedin.com/in/gijskoot"
    # facebook = "url-to-your-facebook"

    # Google Analytics
    # Remove, comment, or leave it blank if you don't have one.
    # ganalytics = "your-google-analytics-tracking-code"

[menu]

    # Menu for the nav bar.
    # There must always be one item present (e.g. home).
    [[menu.main]]
    identifier = "home"
    name       = "home"
    url        = "/"
    weight     = 0

    [[menu.main]]
    identifier = "about"
    name       = "about"
    url        = "/about/"
    weight     = 1
